version: '2.1'

services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch1
    environment:
      - node.name=snowstorm-1
      - cluster.name=snowstorm-cluster
      - cluster.initial_master_nodes=snowstorm-1,snowstorm-2,snowstorm-3
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - discovery.type=zen
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch1:9200"]
      interval: 1s
      timeout: 1s
      retries: 60
    mem_reservation: 4g
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch2
    environment:
      - node.name=snowstorm-2
      - cluster.name=snowstorm-cluster
      - cluster.initial_master_nodes=snowstorm-1,snowstorm-2,snowstorm-3
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - discovery.type=zen
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch2:9200"]
      interval: 1s
      timeout: 1s
      retries: 60
    mem_reservation: 4g
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch3
    environment:
      - node.name=snowstorm-3
      - cluster.name=snowstorm-cluster
      - cluster.initial_master_nodes=snowstorm-1,snowstorm-2,snowstorm-3
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - discovery.type=zen
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch3:9200"]
      interval: 1s
      timeout: 1s
      retries: 60
    mem_reservation: 4g
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay
